kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apphub-role
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apphub-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: apphub-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apphub-role
subjects:
- kind: ServiceAccount
  name: apphub-user
  namespace: default
